[package]
name = "frustum"
version = "0.0.1"
authors = ["Arav Singhal <singhal.arav@gmail.com>"]

[dependencies]
syntex_syntax = "^0.56.0"
syntex_pos = "^0.56.0"
syntex_errors = "^0.56.0"

[lib]
name = "frustum"

[[bin]]
name = "frustum"
path = "src/bin/main.rs"
doc = false
